//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebMarkupMin.Sample.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class CommonHtmlMinificationStrings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"WebMarkupMin.Sample.Resources.CommonHtmlMinificationStrings",
#if NETSTANDARD1_0 || NETSTANDARD1_1 || NETSTANDARD1_2 || NETSTANDARD1_3 || NETSTANDARD1_4 || NETSTANDARD1_5 || NETSTANDARD1_6 || NETCOREAPP1_0 || NET45 || NET451 || NET452 || NET46 || NET461 || NET462 || NET463
				typeof(CommonHtmlMinificationStrings).GetTypeInfo().Assembly
#elif NET40
				typeof(CommonHtmlMinificationStrings).Assembly
#else
#error No implementation for this target
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Doctype, tags and attributes"
		/// </summary>
		public static string ControlGroup_DoctypeTagsAndAttributes
		{
			get { return GetString("ControlGroup_DoctypeTagsAndAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Embedded and inline CSS"
		/// </summary>
		public static string ControlGroup_EmbeddedAndInlineCss
		{
			get { return GetString("ControlGroup_EmbeddedAndInlineCss"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Embedded and inline JavaScript"
		/// </summary>
		public static string ControlGroup_EmbeddedAndInlineJavaScript
		{
			get { return GetString("ControlGroup_EmbeddedAndInlineJavaScript"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "JavaScript templating"
		/// </summary>
		public static string ControlGroup_JavaScriptTemplating
		{
			get { return GetString("ControlGroup_JavaScriptTemplating"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Spaces, comments and CDATA sections"
		/// </summary>
		public static string ControlGroup_SpacesCommentsAndCdataSections
		{
			get { return GetString("ControlGroup_SpacesCommentsAndCdataSections"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "CSS minifier"
		/// </summary>
		public static string DisplayName_CssMinifierName
		{
			get { return GetString("DisplayName_CssMinifierName"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "List of custom Angular 1.X directives with expressions"
		/// </summary>
		public static string DisplayName_CustomAngularDirectiveList
		{
			get { return GetString("DisplayName_CustomAngularDirectiveList"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "JavaScript minifier"
		/// </summary>
		public static string DisplayName_JsMinifierName
		{
			get { return GetString("DisplayName_JsMinifierName"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify Angular 1.X binding expressions"
		/// </summary>
		public static string DisplayName_MinifyAngularBindingExpressions
		{
			get { return GetString("DisplayName_MinifyAngularBindingExpressions"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify embedded CSS code"
		/// </summary>
		public static string DisplayName_MinifyEmbeddedCssCode
		{
			get { return GetString("DisplayName_MinifyEmbeddedCssCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify embedded JavaScript code"
		/// </summary>
		public static string DisplayName_MinifyEmbeddedJsCode
		{
			get { return GetString("DisplayName_MinifyEmbeddedJsCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify inline CSS code"
		/// </summary>
		public static string DisplayName_MinifyInlineCssCode
		{
			get { return GetString("DisplayName_MinifyInlineCssCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify inline JavaScript code"
		/// </summary>
		public static string DisplayName_MinifyInlineJsCode
		{
			get { return GetString("DisplayName_MinifyInlineJsCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify Knockout binding expressions"
		/// </summary>
		public static string DisplayName_MinifyKnockoutBindingExpressions
		{
			get { return GetString("DisplayName_MinifyKnockoutBindingExpressions"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "List of preservable attribute expressions"
		/// </summary>
		public static string DisplayName_PreservableAttributeList
		{
			get { return GetString("DisplayName_PreservableAttributeList"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "List of processable script types"
		/// </summary>
		public static string DisplayName_ProcessableScriptTypeList
		{
			get { return GetString("DisplayName_ProcessableScriptTypeList"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove empty attributes"
		/// </summary>
		public static string DisplayName_RemoveEmptyAttributes
		{
			get { return GetString("DisplayName_RemoveEmptyAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove HTML comments"
		/// </summary>
		public static string DisplayName_RemoveHtmlComments
		{
			get { return GetString("DisplayName_RemoveHtmlComments"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove HTML comments from scripts and styles"
		/// </summary>
		public static string DisplayName_RemoveHtmlCommentsFromScriptsAndStyles
		{
			get { return GetString("DisplayName_RemoveHtmlCommentsFromScriptsAndStyles"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove HTTP protocol from attributes"
		/// </summary>
		public static string DisplayName_RemoveHttpProtocolFromAttributes
		{
			get { return GetString("DisplayName_RemoveHttpProtocolFromAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove HTTPS protocol from attributes"
		/// </summary>
		public static string DisplayName_RemoveHttpsProtocolFromAttributes
		{
			get { return GetString("DisplayName_RemoveHttpsProtocolFromAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove JavaScript protocol from attributes"
		/// </summary>
		public static string DisplayName_RemoveJsProtocolFromAttributes
		{
			get { return GetString("DisplayName_RemoveJsProtocolFromAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove redundant attributes"
		/// </summary>
		public static string DisplayName_RemoveRedundantAttributes
		{
			get { return GetString("DisplayName_RemoveRedundantAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove tags without content"
		/// </summary>
		public static string DisplayName_RemoveTagsWithoutContent
		{
			get { return GetString("DisplayName_RemoveTagsWithoutContent"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Use META charset tag"
		/// </summary>
		public static string DisplayName_UseMetaCharsetTag
		{
			get { return GetString("DisplayName_UseMetaCharsetTag"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Use short DOCTYPE"
		/// </summary>
		public static string DisplayName_UseShortDoctype
		{
			get { return GetString("DisplayName_UseShortDoctype"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "WhitespaceMinificationMode"
		/// </summary>
		public static string DisplayName_WhitespaceMinificationMode
		{
			get { return GetString("DisplayName_WhitespaceMinificationMode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Aggressive whitespace minification"
		/// </summary>
		public static string ListItem_WhitespaceMinificationMode_Aggressive
		{
			get { return GetString("ListItem_WhitespaceMinificationMode_Aggressive"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Medium whitespace minification"
		/// </summary>
		public static string ListItem_WhitespaceMinificationMode_Medium
		{
			get { return GetString("ListItem_WhitespaceMinificationMode_Medium"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Keep whitespace"
		/// </summary>
		public static string ListItem_WhitespaceMinificationMode_None
		{
			get { return GetString("ListItem_WhitespaceMinificationMode_None"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Safe whitespace minification"
		/// </summary>
		public static string ListItem_WhitespaceMinificationMode_Safe
		{
			get { return GetString("ListItem_WhitespaceMinificationMode_Safe"); }
		}

			private static string GetString(string name)
			{
				string value = ResourceManager.GetString(name, _resourceCulture);

				return value;
			}
		}
	}