//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebMarkupMin.Sample.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class HtmlMinificationResources
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"WebMarkupMin.Sample.Resources.HtmlMinificationResources",
#if NETSTANDARD1_0 || NETSTANDARD1_1 || NETSTANDARD1_2 || NETSTANDARD1_3 || NETSTANDARD1_4 || NETSTANDARD1_5 || NETSTANDARD1_6 || NETCOREAPP1_0 || NET451 || NET452 || NET46 || NET461 || NET462 || NET463
				typeof(HtmlMinificationResources).GetTypeInfo().Assembly
#elif NET40
				typeof(HtmlMinificationResources).Assembly
#else
#error No implementation for this target
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Attribute quotes removal mode"
		/// </summary>
		public static string DisplayName_AttributeQuotesRemovalMode
		{
			get { return GetString("DisplayName_AttributeQuotesRemovalMode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Collapse boolean attributes"
		/// </summary>
		public static string DisplayName_CollapseBooleanAttributes
		{
			get { return GetString("DisplayName_CollapseBooleanAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Empty tag render mode"
		/// </summary>
		public static string DisplayName_EmptyTagRenderMode
		{
			get { return GetString("DisplayName_EmptyTagRenderMode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "List of preservable optional tags"
		/// </summary>
		public static string DisplayName_PreservableOptionalTagList
		{
			get { return GetString("DisplayName_PreservableOptionalTagList"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Preserve case of tag and attribute names"
		/// </summary>
		public static string DisplayName_PreserveCase
		{
			get { return GetString("DisplayName_PreserveCase"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove CDATA sections from scripts and styles"
		/// </summary>
		public static string DisplayName_RemoveCdataSectionsFromScriptsAndStyles
		{
			get { return GetString("DisplayName_RemoveCdataSectionsFromScriptsAndStyles"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove CSS type attributes"
		/// </summary>
		public static string DisplayName_RemoveCssTypeAttributes
		{
			get { return GetString("DisplayName_RemoveCssTypeAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove JavaScript type attributes"
		/// </summary>
		public static string DisplayName_RemoveJsTypeAttributes
		{
			get { return GetString("DisplayName_RemoveJsTypeAttributes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Remove optional end tags"
		/// </summary>
		public static string DisplayName_RemoveOptionalEndTags
		{
			get { return GetString("DisplayName_RemoveOptionalEndTags"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "HTML 4.X attribute quotes removal mode"
		/// </summary>
		public static string ListItem_AttributeQuotesRemovalMode_Html4
		{
			get { return GetString("ListItem_AttributeQuotesRemovalMode_Html4"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "HTML5 attribute quotes removal mode"
		/// </summary>
		public static string ListItem_AttributeQuotesRemovalMode_Html5
		{
			get { return GetString("ListItem_AttributeQuotesRemovalMode_Html5"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Keep quotes"
		/// </summary>
		public static string ListItem_AttributeQuotesRemovalMode_KeepQuotes
		{
			get { return GetString("ListItem_AttributeQuotesRemovalMode_KeepQuotes"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Don't add a slash to the empty tag"
		/// </summary>
		public static string ListItem_EmptyTagRenderMode_NoSlash
		{
			get { return GetString("ListItem_EmptyTagRenderMode_NoSlash"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Add a slash to the empty tag"
		/// </summary>
		public static string ListItem_EmptyTagRenderMode_Slash
		{
			get { return GetString("ListItem_EmptyTagRenderMode_Slash"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Add a space and slash to the empty tag"
		/// </summary>
		public static string ListItem_EmptyTagRenderMode_SpaceAndSlash
		{
			get { return GetString("ListItem_EmptyTagRenderMode_SpaceAndSlash"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}