//------------------------------------------------------------------------------
// <auto-generated>
//	 This code was generated by a tool.
//
//	 Changes to this file may cause incorrect behavior and will be lost if
//	 the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebMarkupMin.Sample.Resources
{
	using System;
	using System.Globalization;
	using System.Reflection;
	using System.Resources;

	/// <summary>
	/// A strongly-typed resource class, for looking up localized strings, etc.
	/// </summary>
	public class MinificationStrings
	{
		private static Lazy<ResourceManager> _resourceManager =
			new Lazy<ResourceManager>(() => new ResourceManager(
				"WebMarkupMin.Sample.Resources.MinificationStrings",
#if NET40
				typeof(MinificationStrings).Assembly
#else
				typeof(MinificationStrings).GetTypeInfo().Assembly
#endif
			));

		private static CultureInfo _resourceCulture;

		/// <summary>
		/// Returns a cached ResourceManager instance used by this class
		/// </summary>
		public static ResourceManager ResourceManager
		{
			get
			{
				return _resourceManager.Value;
			}
		}

		/// <summary>
		/// Overrides a current thread's CurrentUICulture property for all
		/// resource lookups using this strongly typed resource class
		/// </summary>
		public static CultureInfo Culture
		{
			get
			{
				return _resourceCulture;
			}
			set
			{
				_resourceCulture = value;
			}
		}

		/// <summary>
		/// Looks up a localized string similar to "Minify"
		/// </summary>
		public static string ButtonText_Minify
		{
			get { return GetString("ButtonText_Minify"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minification duration"
		/// </summary>
		public static string DisplayName_MinificationDuration
		{
			get { return GetString("DisplayName_MinificationDuration"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minified content"
		/// </summary>
		public static string DisplayName_MinifiedContent
		{
			get { return GetString("DisplayName_MinifiedContent"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Minified size"
		/// </summary>
		public static string DisplayName_MinifiedSize
		{
			get { return GetString("DisplayName_MinifiedSize"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Style of the newline"
		/// </summary>
		public static string DisplayName_NewLineStyle
		{
			get { return GetString("DisplayName_NewLineStyle"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Original size"
		/// </summary>
		public static string DisplayName_OriginalSize
		{
			get { return GetString("DisplayName_OriginalSize"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Preserve newlines"
		/// </summary>
		public static string DisplayName_PreserveNewLines
		{
			get { return GetString("DisplayName_PreserveNewLines"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Saved"
		/// </summary>
		public static string DisplayName_Saved
		{
			get { return GetString("DisplayName_Saved"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Source code"
		/// </summary>
		public static string DisplayName_SourceCode
		{
			get { return GetString("DisplayName_SourceCode"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "You did not fill field &quot;{0}&quot;."
		/// </summary>
		public static string ErrorMessage_FormFieldIsNotFilled
		{
			get { return GetString("ErrorMessage_FormFieldIsNotFilled"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "The field &quot;{0}&quot; must be a string with a maximum length of {1:N0}."
		/// </summary>
		public static string ErrorMessage_FormFieldValueTooLong
		{
			get { return GetString("ErrorMessage_FormFieldValueTooLong"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Auto-detect style for newline based on the source input"
		/// </summary>
		public static string ListItem_NewLineStyle_Auto
		{
			get { return GetString("ListItem_NewLineStyle_Auto"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Force the Macintosh style for newline (CR)"
		/// </summary>
		public static string ListItem_NewLineStyle_Mac
		{
			get { return GetString("ListItem_NewLineStyle_Mac"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "CRLF in Windows, LF on other platforms"
		/// </summary>
		public static string ListItem_NewLineStyle_Native
		{
			get { return GetString("ListItem_NewLineStyle_Native"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Force the Unix style for newline (LF)"
		/// </summary>
		public static string ListItem_NewLineStyle_Unix
		{
			get { return GetString("ListItem_NewLineStyle_Unix"); }
		}

		/// <summary>
		/// Looks up a localized string similar to "Force the Windows style for newline (CRLF)"
		/// </summary>
		public static string ListItem_NewLineStyle_Windows
		{
			get { return GetString("ListItem_NewLineStyle_Windows"); }
		}

		private static string GetString(string name)
		{
			string value = ResourceManager.GetString(name, _resourceCulture);

			return value;
		}
	}
}